### ISSUE TITLE
Refactor tabular module to be more understandable

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes#103]
Scenare:
1) mame vstupni schema castecne definovane
2) nemame vstupni schema

TableSchema - representuje aktualni stav table schema, ktere lze konzistentne rozsirovat
   - kdykoli se pokusime stav zmenit nekonzistentne tak to objekt nedovoli a poskytne srozumitelnou hlasku
   - obsahuje api pro uzaver schematu -- napriklad kdyz neni specifikovany namespace pro sloupce, tak si vymysli

A/C:
- je implemetovany srozumitelny diff mezi expectedSchema a actualSchema
- an example output of SPipes processing which shows diff is put here (just to judge informativeness of error message in the context)

**Comment by blcham** [comment]
How nice are validation constrains now in CSAT:

```
sp:text """# 1 - there is an additional column in retrieved input data schema compared to expected one
SELECT ?actualColumn
WHERE {
     ?actualTableSchema  a  csvw:TableSchema . 
     ?expectedTableSchema  a  csvw:TableSchema .
     FILTER( ?actualTableSchema != ?expectedTableSchema)
     
     ?actualTableSchema csvw:column/csvw:propertyUrl ?actualColumn .
     BIND(iri(?actualColumn) as ?actualColumnIRI)
     
     FILTER NOT EXISTS {
          ?expectedTableSchema csvw:column/kbss-csvw:property ?actualColumnIRI .
     }
}"""
```

```
      sp:text """# 2 - there is missing column in retrieved input data compared to expected one
SELECT ?expectedColumnIRI
WHERE {
     ?actualTableSchema  a  csvw:TableSchema .
     ?expectedTableSchema  a  csvw:TableSchema .
     FILTER( ?actualTableSchema != ?expectedTableSchema)

     ?expectedTableSchema csvw:column/kbss-csvw:property ?expectedColumnIRI .

     FILTER NOT EXISTS {
          ?actualTableSchema csvw:column/csvw:propertyUrl ?actualColumn .
          FILTER(str(?expectedColumnIRI) = ?actualColumn)
     }
}""" ;
```

**Comment by blcham** [comment]
Method prototyping:
```
            tableSchema.setCompleteColumnSet(List<Columns> columnNames) {
                if (columnSet empty) {
                    //just set it
                } else {
                    // check it is complete or generate informative message
                }
            }
```

**Comment by blcham** [comment]
@Matthew-Kulich A/C here were implemented? So I will receive in log the diff between expected and actual columns?

**Comment by Matthew-Kulich** [comment]
@blcham well, I realize they weren't. But at the moment we extend one schema, we don't have 2 of them. So I presume that we want to see the difference at the end of the tabular module?

**Comment by blcham** [comment]
Not sure what you mean end of tabular module. I thought that at some point you call something like tabularSchema.setCompleteSetOfColums(List/Set columns) and in this method it fails if it was assigned in table schema already ... and describe appropriately the diff ... we discussed it in some thread i believe ... 


does it make sense?

**Comment by Matthew-Kulich** [comment]
I see what you mean I guess

"it fails if it was assigned in table schema already and is not consistent extension" 
-> that means that we have columns already from the input schema and these columns don't correspond to the columns from input data -> so we describe the diff, am I right?

Well, I can rewrite that

**Comment by blcham** [comment]
Yes this is exactly what are those sparql queries doing -- https://github.com/kbss-cvut/s-pipes/issues/103#issuecomment-1237962133.

**Comment by blcham** [comment]
@Matthew-Kulich I have added A/C here:
> an example output of SPipes processing which shows diff is put here (just to judge informativeness of error message in the context)

**Comment by Matthew-Kulich** [comment]
This is error messages now, so we want to make it more informative. 

![image](https://user-images.githubusercontent.com/67843655/190365494-9c3a6fdd-db0c-4651-b13c-fc271fca3cc8.png)


![image](https://user-images.githubusercontent.com/67843655/190365579-60059ccd-56e9-42c8-a8a3-c2cd962be182.png)

**Comment by blcham** [comment]
It would be great to show which are additional and which are missing. You can take such message to the owner of CSV without further explaining it ...

**Comment by Matthew-Kulich** [comment]
Ok I see

**Comment by Matthew-Kulich** [comment]
What do you think about these error messages? @blcham 

Missing columns: 
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/67843655/191749827-6817f20b-0bf3-46bd-979e-9dcebce45ef0.png">

Additional columns:
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/67843655/191750346-1687b51d-5e8c-4a35-9cee-b704cdf415b8.png">

Maybe we can also add the comparison between data-based and schema-based columns.
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/67843655/191753631-bd6fea9f-2517-4d79-b173-a553fd4d5ccd.png">

**Comment by blcham** [comment]
I am not sure why we would need such detailed information related to columns. I believe we should only show strings that occur in CSV file i.e. "Start Date", "End Date" etc ... and what we expected to be there ... I am not sure how we would use other information. 

Imagine typical use case, when a column is added or removed. You want to know ASAP identify how CSV look and what you expected the CSV to look.

**Comment by Matthew-Kulich** [comment]
Alright, I see the point.  So this one should be better
![image](https://user-images.githubusercontent.com/67843655/192250027-20ce05e4-80aa-4e40-89dd-3e59759469a7.png)
