### ISSUE TITLE
Implement module to retrieve prefix mapping of loaded ontologies

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes#115]
Motivation:
- we want to be able to create validation pipelines of existing workspace (= set of script dirs) w.r.t. prefixes (e.g. if there is a collision)

My suggestion:
- we could have a module that returns metadata of all ontologies loaded in the workspace
- metadata would include file-path related to script roots, prefix mappings etc.

A/C:
- (1) search for rdf vocabularies that would provide us model for 'is-located-in-file', 'has-prefix' vocabulary (e.g. something like https://vocab.org/vann/#preferredNamespacePrefix). Jena has prefix mapping model as well, so it should be reviewed too.
- design vocabulary (model) for annotation of ontologies from workspace. Based on research from [1], it should use existing rdf vocabulary terms or it could be entirely new one.
- module is implemented and returns metadata of loaded scripts

**Comment by rodionnv** [comment]
I would like to ask, module should parse content of the script and then return metadata as Jena RDF Model with triples [ontology has-prefix prefix]? Jena's PrefixMapping creates map<String, String> but as I understand, we need a rdf model?

**Comment by blcham** [comment]
correct

**Comment by blcham** [comment]
See related documentation in:
ImportRDFFromWorkspaceModule.java

**Comment by rodionnv** [comment]
@blcham looks like this is done in [RetrievePrefixModule](https://github.com/kbss-cvut/s-pipes/blob/4ca8d306c6436702209a8cdeb9ebb3409fef5a26/s-pipes-core/src/main/java/cz/cvut/spipes/modules/RetrievePrefixesModule.java)

**Comment by blcham** [comment]
I believe that some parts are missing:
1) https://github.com/kbss-cvut/s-pipes/blob/4ca8d306c6436702209a8cdeb9ebb3409fef5a26/s-pipes-core/src/main/java/cz/cvut/spipes/modules/RetrievePrefixesModule.java#L16

There is no documentation here, i would like to see some info what module does including some example output in this comment.

2) https://github.com/kbss-cvut/s-pipes/blob/4ca8d306c6436702209a8cdeb9ebb3409fef5a26/s-pipes-core/src/test/java/cz/cvut/spipes/modules/RetrievePrefixesModuleTest.java#L67 

This test does not do anything, it just writes to the output. Instead some assert about the output should be added.
E.g. you can have file that defines expected output and then do assertIsomorphic(actualModel, expectedModel) in a same way as it is done in https://github.com/kbss-cvut/s-pipes/blob/4ca8d306c6436702209a8cdeb9ebb3409fef5a26/s-pipes-modules/module-tabular/src/test/java/cz/cvut/spipes/modules/TabularModuleTest.java#L200.

**Comment by blcham** [comment]
Resolved by https://github.com/kbss-cvut/s-pipes/pull/190.
