### ISSUE TITLE
Fix diff in tabular module

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes#123]
![image](https://user-images.githubusercontent.com/3962237/194771837-a9e27424-d121-40cc-9f97-24d260372279.png)

A/C:
- issues on the image above are fixed 
- also issue raised in https://github.com/kbss-cvut/s-pipes/pull/121 are fixed
- (optional nice to have if easy to implement) order of expected columns should be ordered by actual column if we don't have order in schema assumed

**Comment by blcham** [comment]
So we have the following options:
1) Use titles if they are available in both schemas and names otherwise
2) use only names

Both options are ok with me.

**Comment by Matthew-Kulich** [comment]
Im not sure what you mean by "also issue raised in https://github.com/kbss-cvut/s-pipes/pull/121 are fixed"

**Comment by blcham** [comment]
> 

There are 4 of my comments that were not resolved as you did not comment on it (as if it is done/won't be fixed, or something else)

**Comment by blcham** [comment]
> Im not sure what you mean by "also issue raised in #121 are fixed"

There are 4 of my comments that were not resolved as you did not comment on it (as if it is done/won't be fixed, or something else)
