### ISSUE TITLE
Add generic csv to rdf module

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes#15]
CSV module should be compliant with [W3C specification for csv2rdf](https://www.w3.org/TR/csv2rdf) (see also [related W3C primer](https://www.w3.org/TR/tabular-data-primer/)).
See also [related project](https://etl.linkedpipes.com/components/t-tabular).
Most of the source-code can be taken from: https://github.com/tarql/tarql

A/C: 
- should support validation of empty columns
- should support delimiter COMMA and TAB

**Comment by blcham** [comment]
We are interested in "7.1 Simple example" of https://www.w3.org/TR/csv2rdf,

**Comment by blcham** [comment]
[Model for Tabular Data and Metadata on the Web](https://www.w3.org/TR/2015/REC-tabular-data-model-20151217/)

**Comment by Sidonivs** [comment]
step 1 - column property url should be prefixed by dataPrefix
step 2 - Schema should be included in output
step 3 - Custom schema
step 4 - mapping csvw model to model in Java

**Comment by blcham** [comment]
@Matthew-Kulich tagging u here just so u have reference to input materials for the module, this is done so closing the ticket.
