### ISSUE TITLE
Remove dependance external RDF definitions

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes#170]
Currently, RDF definitions are external to the s-pipes project. It is in gitblit/s-forms-modules.

The goal:
- remove [dependence on gitblit/s-forms-modules](https://github.com/kbss-cvut/s-pipes/blob/c8abb32e5e39cd6b22e76c74857a76e62b53ee93/Dockerfile#LL13C25-L13C80) when creating docker image.

**Comment by 0-Tikaro** [comment]
Test

**Comment by blcham** [comment]
done
