### ISSUE TITLE
Refactor SPipesUtil in s-pipes-forms to work with all subclasses of sp:Command

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/s-pipes#195]
Refactor `s-pipes-forms` `SPipesUtil  `to work with all subclasses of sp:Command
Use the ontology in `form-ontology/sp.ttl` in resources.
Refactor code that uses SPipesUtil .

**Comment by blcham** [comment]
Should be solved by https://github.com/kbss-cvut/s-pipes/pull/196
