### ISSUE TITLE
s-pipes-module-creator-maven-plugin does not Generate RDF Description for Some Java Based s-pipes Modules in s-pipes-modules 

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/s-pipes#206]
To generate RDF s-pipes module description the `s-pipes-module-creator-maven-plugin` requires the java classes implementing the s-pipes module be annotated with `@SPipesModule` annotation and their parameters be annotated with the `@Parameter` annotation.

The following sub projects of `s-pipes-modules` do not specify any `@SPipesModule` annotations on module classes:
`module-ckan2rdf`
`module-dataset-discovery`
`module-eccairs`
`module-form`
`module-identity`
`module-nlp`
`module-rdf4j`
`module-rdfstream`
`module-security`
`module-sparql-endpoint`
`module-tarql`

Add appropriate `@Parameter` annotations on properties of each model.

The following sub projects of `s-pipes-modules` do not specify any parameter using the `@Parameter` annotation:

`module-dataset-discovery`
`module-eccairs`
`module-identity`
`module-nlp`
`module-rdf4j`
`module-rdfstream`
`module-security`
`module-tabular`
`module-tarql`

Add appropriate `@SPipesModule` annotations on module classes.

**Comment by blcham** [comment]
@kostobog Just a note here. I am not sure if we are able to replace generation fully using annotations in Java -- we might need to do it incrementally with the use of manually written ttl files that define SPipes modules.
