### ISSUE TITLE
Implement spif:parseDate

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes#21]
- investigate whether whole spif functions can imported to the s-pipes
- in case it cannot be imported implement spif:parseDate
- you can see [implementation in RDF4j](https://rdf4j.org/javadoc/latest/index.html?org/eclipse/rdf4j/spin/function/spif/ParseDate.html)
- there is implementation of similar functions in Jena
   -  [XSDFuncOp.java in Jena](https://jena.apache.org/documentation/javadoc/arq/org/apache/jena/sparql/expr/nodevalue/XSDFuncOp.html)
   - [other sparql functions](https://jena.apache.org/documentation/javadoc/arq/org/apache/jena/sparql/function/)
   - [Jena ARQ documentation](https://jena.apache.org/documentation/query/index.html)
   
- Subgoal of the task is to find out what functions can be reused from Jena

**Comment by blcham** [comment]
It is required for time-analysis CSV.

**Comment by blcham** [comment]
```
spif:parseDate
  rdf:type spin:Function ;
  spin:constraint [
      rdf:type spl:Argument ;
      spl:optional "true"^^xsd:boolean ;
      spl:predicate arg:patternLanguage ;
      spl:valueType xsd:string ;
      rdfs:comment "The code of the language (e.g. \"de\" for German) to use for parsing." ;
    ] ;
  spin:constraint [
      rdf:type spl:Argument ;
      spl:predicate arg:pattern ;
      spl:valueType xsd:string ;
      rdfs:comment "The template of the input string. This must conform to the pattern language implemented by the Java SimpleDateFormat class (http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html)." ;
    ] ;
  spin:constraint [
      rdf:type spl:Argument ;
      spl:predicate sp:arg1 ;
      spl:valueType xsd:string ;
      rdfs:comment "the input text" ;
    ] ;
  spin:returnType rdfs:Literal ;
  rdfs:comment "Converts a string in a semi-structured format into a xsd:date, xsd:dateTime or xsd:time literal. The input string must be in a given template format, e.g. \"yyyy.MM.dd G 'at' HH:mm:ss z\" for strings such as 2001.07.04 AD at 12:08:56 PDT." ;
  rdfs:label "parse date" ;
  rdfs:subClassOf spl:DateFunctions ;
.
spif:prefix
  rdf:type spin:MagicProperty ;
  spin:constraint [
      rdf:type spl:Argument ;
      spl:predicate sp:arg1 ;
      spl:valueType xsd:string ;
      rdfs:comment "The namespace (string) or an unbound variable." ;
    ] ;
  spin:returnType xsd:string ;
  rdfs:comment "Can be used to get namespaces and their prefixes. This magic property takes the namespace (string) or a variable on the left and a prefix or a variable on the right. If both are unbound variables, then it will iterate over all namespaces and their prefixes. Otherwise it will bind the namespace or prefix. If both are bound, the system checks whether the given prefix is for the given namespace." ;
  rdfs:label "prefix" ;
  rdfs:subClassOf spin:MagicProperties ;
.
```

**Comment by blcham** [comment]
There is interesting implementation in Jena class `org.apache.jena.sparql.expr.nodevalue.XSDFuncOp.java`:
```
public static NodeValue dateTimeCast(NodeValue nv, XSDDatatype xsd) {
````

**Comment by blcham** [comment]
Just to get better context i suggest to [find out what is difference between Graph and Model](https://jena.apache.org/documentation/rdf/index.html).

**Comment by Matthew-Kulich** [comment]
Pattern "kk" includes hours from interval [1,24] but we want to use "H" which is from interval [0,23] so there will no longer be problems with after midnight time.

**Comment by Matthew-Kulich** [comment]
Regarding bad pattern and non-literal value there are still exceptions. If this will make problems, we can change that.
