### ISSUE TITLE
Revise comment field values of Parameter annotation

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/s-pipes#218]
Revise comment field values of Parameter annotation - see TODOs in commit [Mark comment field value of Parameter annotations that need to be revised/improved](https://github.com/kbss-cvut/s-pipes/pull/210/commits/7152270bee474eded021edeed438d8d5b6b614a6)

**Comment by blcham** [comment]
https://github.com/kbss-cvut/s-pipes/pull/221
