### ISSUE TITLE
Use annotations to inject LOG

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes#244]
Refactor code to use annotation instead of definition in a private static field.

**Comment by palagdan** [comment]
@blcham I suggest to close this issue because of impossibility to inject logger with custom name like LOG(in our case). It has reserved name 'log' . From: https://projectlombok.org/features/log documentation.

> You put the variant of @Log on your class (whichever one applies to the logging system you use); you then have a static final log field, initialized as is the commonly prescribed way for the logging framework you use, which you can then use to write log statements.

**Comment by blcham** [comment]
I do not care about renaming LOG --> log if this is the issue.

**Comment by palagdan** [comment]
@blcham  ok then, I will also refactor LOG variable to log in each class where it is used.

**Comment by blcham** [comment]
Changes were reverted.
