### ISSUE TITLE
Add constants instead of raw values to attribute name  in @parameter annotation 

### ISSUE THREAD

**Issue by palagdan** [kbss-cvut/s-pipes#258]
Raw values in attribute `name` should be changed to constant
![Screenshot from 2024-08-15 15-01-17](https://github.com/user-attachments/assets/5ad95573-a3bf-4677-8b9f-d36f3f0898e0)

**Comment by palagdan** [comment]
@blcham

We have two options for solving this:

We can add a Property parameter to the @Parameter annotation. This parameter will be optional, allowing users to provide a Property directly instead of using a prefix and name.

Alternatively, we can create a separate file specifically for constants such as replace, value, selects, etc.

**Comment by blcham** [comment]
I believe it does not come with price of adding new dependencies, so i would go with adding `Property` named e.g. `url`.

**Comment by palagdan** [comment]
blocked by #219

**Comment by blcham** [comment]
@palagdan not blocked anymore

**Comment by palagdan** [comment]
@blcham 

Property is an interface so we cannot add it to the annotation because it requires a constant value in a compile time. So we have only one options to make constants for names(replace , is-parse-text etc).

**Comment by blcham** [comment]
I suggest to remove urlPrefix and name parameter of @Parameter annotation and instead introduce `iri` parameter as can be found in initial PR. What do you think?
