### ISSUE TITLE
Support CSV files without header

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes#26]
As a user of the module I want to be able to configure module to skip initial header.

A/C:
- if configuration is ("skip-header=true") and (RDF description of schema is provided in input graph) 
   - we infer CVS schema from the nput rdf graph
   - we create artificial schema based on column position (should be part of the W3C specification) (e.g. :column_1, :column_2 ...)
- if configuration is ("skip-header=false") and (RDF description of schema is provided in input graph)
   - we check that CSV schema is compliant with the one provided in rdf input graph

Depends on task #25.

**Comment by Matthew-Kulich** [comment]
Ok, thanks.

Regarding column names, if the names will be saved in the custom schema, we will not know the right order, because we get columns as Set.

**Comment by blcham** [comment]
Not sure if i understood correctly, but schema can also contain information about the order. I would think there is a property such (just guessing):
csw:column -- can represent columns as a set
csw:columns -- can order those columns.

**Comment by Matthew-Kulich** [comment]
Alright, i will add the property csvw:columns (doesn't exist now)

**Comment by blcham** [comment]
@Matthew-Kulich I assume we can close it.

**Comment by Matthew-Kulich** [comment]
@blcham Yes
