### ISSUE TITLE
Refactor toString method to separate  Utils Class  for converting RDFNode values to the readable string

### ISSUE THREAD

**Issue by palagdan** [kbss-cvut/s-pipes#263]
![Screenshot from 2024-08-19 16-21-44](https://github.com/user-attachments/assets/792c4852-ec01-448c-867a-1b57c94e528f)

Related to #76 

In ticket #76, the solution addressed only the output for the VariableBindings class. In this ticket, the toString method should be refactored into a separate Utils class so that it can be used in other places.

**Comment by palagdan** [comment]
@blcham

**Comment by blcham** [comment]
Reopening this issue because I do not understand how it is related to the picture above. If merged PR was only refactoring, it should not affect the picture above. Moreover, I do not think that fixing picture above is related to code from PR.

**Comment by blcham** [comment]
We can close this issue after following comment is satisfied: https://github.com/kbss-cvut/s-pipes/pull/264#issuecomment-2301499934
