### ISSUE TITLE
Fix parseDate tests

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes#49]
Now tests are disabled, please enable it and fix:
https://github.com/kbss-cvut/s-pipes/pull/48

**Comment by Matthew-Kulich** [comment]
Tests are working with Java 11. Should I fix it despite upgrading to java 11 (#47) later?

**Comment by blcham** [comment]
@Matthew-Kulich sorry my bet i did not realize, closing this issue.
