### ISSUE TITLE
Optimize development enviroment for s-pipes scripts

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes#50]
Goal is to provide environment for developing SPipes scripts in file system, that would provide effective way to debug scripts.

Related implementation detail (see `config-core.properties`):
```
contextsLoader.data.keepUpdated=true
execution.environment=development
execution.developmentServiceUrl=http://localhost:8080/s-pipes
```

Main blocker now is that when user modify ttl file of a script with `contextsLoader.data.keepUpdated=true`, it loads all the ttl files instead of loading only changed ttl files. There are two possible strategies to "keep files updated":
1) execution triggered scripts update  -- easy to implement, as we just need before the execution check all relevant files if they changed (check modification date/md5 hash?). 
     - pros: it can be targeted to only relevant files for execution
     - pros: does not cosume that much resources as variant 2)
2) modification triggered scripts update -- much harder to implement, because we need to listen within filesystem for changes. This was however already implemented in SPipes Editor.
    - pros:  it can be directly used for SPipes Editor (we need to revise architecture)

My proposal of next step:
- implement variant 1 (1 timestamp for ontology manager, all files newer than timestamp are updated)
- discuss implementation of variant 2 (95% of efforts needed to implement variant 1 should be reused here)

Issues with variant 1:
- if file is deleted --> we won't be able to find the file (exception is thrown)
- if file is added --> we won't see related ontology and thus "execute" can return with script function not found
- if import is added/deleted --> thus file is changed ...

**Comment by Matthew-Kulich** [comment]
When the file is deleted, do we want to also check missing .ttl files and not only .sms.ttl ? 
In current state we get this exception `org.apache.jena.shared.NotFoundException: Not found: http://onto.fel.cvut.cz/ontologies/s-pipes/examples/constraint-validation/people`. But i guess we want to throw FileNotFoundException, right? @blcham

**Comment by blcham** [comment]
we should consider all .ttl files.
