### ISSUE TITLE
Runtime does not work with Java 11

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes#57]
When running a pipline in Java 11, I get following errors:
- SPipes doc pipeline for valiadation-constraints -- I would start with that:
[error-0.log](https://github.com/kbss-cvut/s-pipes/files/8310857/error-0.log)
- csat pipeline for time-analysis:
[error-1.log](https://github.com/kbss-cvut/s-pipes/files/8310850/error-1.log)

**Comment by blcham** [comment]
This claims to provide solution for that:
https://stackoverflow.com/questions/58009038/eclipse-4-12-java-lang-classnotfoundexception-com-sun-xml-internal-bind-v2-co

**Comment by Matthew-Kulich** [comment]
It is already fixed on main branch. So i will just merge it to feature branch

**Comment by blcham** [comment]
Ok, I just did, thanks.
