### ISSUE TITLE
Log prefix issues in imported ontologies

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes#86]
When importing UFO ontology in SPipes scripts it causes very strange issues from time to time while executing `sp:Select`, `sp:Ask` or `sp:Construct` queries. It sometimes generates incorrect prefixes which I assume is imported by the UFO ontology.

It results in a query parse error due to the invalid prefix in the query:
```
PREFIX See: <http://www.geneontology.org/formats/oboInOwl#303 See >
```

As can be seen, there is " " (space) in the URL prefixed by "See". The UFO ontology is imported by the triple:
```
?o owl:imports <http://onto.fel.cvut.cz/ontologies/ufo> ;
```

The goal of the prefix is to improve the detection of the issue. It can be done using 2 mechanisms:
1. Log which ontology has problematic triples. Currently, the UFO ontology generates the following warnings, but since it is in an imported ontology, it is unclear that this particular ontology caused the warning.
```
WARN  org.apache.jena.riot - [line: 13, col: 47] {W124} Non-ascii characters in a namespace URI may not be completely portable: <http://www.geneontology.org/formats/oboInOwl#303 See >. Resulting RDF URI references are legal.
```
It is important to find out which ontology is causing the issue from the log.

2. Test that the prefixes are ok after loading a particular ontology. This should be done during the deployment. Thus after the ontology is loaded it should be checked that all its "transitive imports" did not bring any invalid prefix.

A/C:
- at least one logging improvement is implemented (i.e. [1] or [2], ideally both)
- error in UFO ontologies is found (maybe @kostobog can help to point to repository where ufo ontologies are located)

**Comment by blcham** [comment]
The issue can be tested on the following ontology:
[test-spin-issue.zip](https://github.com/kbss-cvut/s-pipes/files/9128409/test-spin-issue.zip)

**Comment by Matthew-Kulich** [comment]
Closed via #92

**Comment by blcham** [comment]
Can you somehow comment on satisfying "A/C"?

**Comment by Matthew-Kulich** [comment]
> at least one logging improvement is implemented (i.e. [1] or [2], ideally both)

After getting the ontology and saving it to the model we check all model prefixes if they are correct

> error in UFO ontologies is found (maybe @kostobog can help to point to a repository where ufo ontologies are located)

Forgot about that, I'll write Bogdan

**Comment by Matthew-Kulich** [comment]
Error found and fixed.  ( [commit link](https://kbss.felk.cvut.cz/gitblit/commit/ufo.git/a6e45954077cbb57e4a347f013af087a65d0475b) )
